#!/bin/bash
# ----------------------------------------------------------------------------
# Copyright (c) 2019 by Burkhardt Renz. All rights reserved.
# Makes App for Mac OSX
# ----------------------------------------------------------------------------

# Javapackager creates an app, that doesn't use the QuitHandler and the AboutHandler
# i.e. it can't be used

# use this instead:
# java -Duser.language=en -Xdock:name=lwb-gui -jar lwb-gui.jar

javapackager -deploy -name lwb-gui -appclass lwb_gui.main \
	-native image -outdir target -outfile lwb-gui \
	-srcdir ./target -srcfiles lwb-gui.jar \
	-Bruntime=/Library/Java/JavaVirtualMachines/jdk-9.jdk \
	-Bicon=lwb.icns \
	-BjvmOptions=-Duser.language=en \
	-BjvmOptions=-Xdock:name=lwb.gui \
	-title lwb-gui -nosign -v
